taskManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task_manager/urls.py
from django.urls import path

from task_manager.views import (
    index,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    PositionListView,
    PositionDetailView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView
)

urlpatterns = [
    path("", index, name="index"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task-types/<int:pk>/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("task-types/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path("task-types/<int:pk>/update/", TaskTypeUpdateView.as_view(), name="task-type-update"),
    path("task-types/<int:pk>/delete/", TaskTypeDeleteView.as_view(), name="task-type-delete"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="position-detail"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path("positions/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("positions/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),
]

app_name = "task_manager"

task_manager/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Position(models.Model):
    name = models.CharField(max_length=100, unique=True)


class Worker(AbstractUser):
    position = models.ForeignKey(Position, on_delete=models.SET_NULL, null=True, related_name="workers")


class TaskType(models.Model):
    name = models.CharField(max_length=100, unique=True)


class Task(models.Model):
    PRIORITY_CHOICES = [
        ('Urgent', 'Urgent'),
        ('High', 'High'),
        ('Medium', 'Medium'),
        ('Low', 'Low')
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES)
    task_type = models.ForeignKey(TaskType, on_delete=models.SET_NULL, null=True, related_name="tasks")
    assignees = models.ManyToManyField(Worker, related_name="tasks")

task_manager/forms.py
from django import forms


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by task name"}
        )
    )

class TaskTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by task type"}
        )
    )

class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by worker name"}
        )
    )

class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by position name"}
        )
    )

task_manager/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from task_manager.forms import (
    TaskSearchForm,
    PositionSearchForm,
    WorkerSearchForm,
    TaskTypeSearchForm
)
from task_manager.models import (
    Position,
    Worker,
    TaskType,
    Task
)


def index(request):
    """View function for the home page of the site."""

    num_workers = Worker.objects.count()
    num_tasks = Task.objects.count()
    num_task_types = TaskType.objects.count()
    num_positions = Position.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_workers": num_workers,
        "num_tasks": num_tasks,
        "num_task_types": num_task_types,
        "num_positions": num_positions,
        "num_visits": num_visits + 1
    }

    return render(request, "task_manager/index.html", context=context)


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 5
    queryset = Task.objects.select_related("task_type")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = TaskSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        model = self.request.GET.get("model")
        if model:
            return Task.objects.filter(model__icontains=model)
        return Task.objects.all()


class TaskDetailView(generic.DetailView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")


class PositionListView(generic.ListView):
    model = Position
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = PositionSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return Position.objects.filter(name__icontains=name)
        return Position.objects.all()


class PositionDetailView(generic.DetailView):
    model = Position


class PositionCreateView(generic.CreateView):
    model = Position
    success_url = reverse_lazy("task_manager:position-list")


class PositionUpdateView(generic.UpdateView):
    model = Position
    success_url = reverse_lazy("task_manager:position-list")


class PositionDeleteView(generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task_manager:position-list")


class WorkerListView(generic.ListView):
    model = Worker
    paginate_by = 5
    queryset = Worker.objects.select_related("position")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = WorkerSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return Worker.objects.filter(name__icontains=name)
        return Worker.objects.all()


class WorkerDetailView(generic.DetailView):
    model = Worker


class WorkerCreateView(generic.CreateView):
    model = Worker
    success_url = reverse_lazy("task_manager:worker-list")


class WorkerUpdateView(generic.UpdateView):
    model = Worker
    success_url = reverse_lazy("task_manager:worker-list")


class WorkerDeleteView(generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("task_manager:worker-list")


class TaskTypeListView(generic.ListView):
    model = TaskType
    paginate_by = 5
    template_name = "task_manager/task_type_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = TaskTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return TaskType.objects.filter(name__icontains=name)
        return TaskType.objects.all()


class TaskTypeDetailView(generic.DetailView):
    model = TaskType
    template_name = "task_manager/task_type_detail.html"



class TaskTypeCreateView(generic.CreateView):
    model = TaskType
    template_name = "task_manager/task_type_form.html"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskTypeUpdateView(generic.UpdateView):
    model = TaskType
    template_name = "task_manager/task_type_form.html"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskTypeDeleteView(generic.DeleteView):
    model = TaskType
    template_name = "task_manager/task_type_confirm_delete.html"
    success_url = reverse_lazy("task_manager:task-type-list")

templates/task_manager/index.html
{% extends "base.html" %}

{% block content %}
	<h1>Task Manager Home</h1>
	<p>Welcome to Best Task Manager!</p>
	<h2>Dynamic content</h2>
	<p>The Task Manager has the following record counts:</p>
	<ul>
		<li><strong>Workers:</strong> {{ num_workers }}</li>
		<li><strong>Tasks:</strong> {{ num_tasks }}</li>
		<li><strong>Task types:</strong> {{ num_task_types }}</li>
		<li><strong>Positions:</strong> {{ num_positions }}</li>
	</ul>

	<p>You have visited this page
		{{ num_visits }} time{{ num_visits|pluralize }}.
	</p>

{% endblock %}

templates/task_manager/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete position?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task_manager/position_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ position.name }}
    <a href="{% url 'task_manager:position-delete' pk=position.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'task_manager:position-update' pk=position.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
{% endblock %}

templates/task_manager/position_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} position</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/position_list.html
{% extends "base.html" %}

{% block content %}
	<h1>
		Position list
		<a href="{% url 'task_manager:position-create' %}" class="btn btn-primary link-to-page">
			Create
		</a>
	</h1>
	<form method="get" action="">
		{{ search_form }}
		<input type="submit" value="Search" class="btn btn-primary">
	</form>
	{% if position_list %}
		<ul>
			{% for position in position_list %}
				<li>
					<a href="{% url "task_manager:position-detail" pk=position.id %} ">{{ position.id }}</a>
					{{ position.name }}
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>There are no positions in task_manager</p>
	{% endif %}
{% endblock %}

templates/task_manager/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ task.name }}
    <a href="{% url 'task_manager:task-delete' pk=car.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'task_manager:task-update' pk=car.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
{% endblock %}

templates/task_manager/task_list.html
{% extends "base.html" %}

{% block content %}
	<h1>
		Task list
		<a href="{% url 'task_manager:task-create' %}" class="btn btn-primary link-to-page">
			Create
		</a>
	</h1>
	<form method="get" action="">
		{{ search_form }}
		<input type="submit" value="Search" class="btn btn-primary">
	</form>
	{% if task_list %}
		<ul>
			{% for task in task_list %}
				<li>
					<a href="{% url "task_manager:task-detail" pk=task.id %} ">{{ task.id }}</a>
					{{ task.name }}
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>There are no tasks in task_manager</p>
	{% endif %}
{% endblock %}

templates/task_manager/task_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task type?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task_manager/task_type_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ task_type.name }}
    <a href="{% url 'task_manager:task-type-delete' pk=task_type.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'task_manager:task-type-update' pk=task_type.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
{% endblock %}

templates/task_manager/task_type_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete worker?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task_manager/worker_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ worker.username }}
    <a href="{% url 'task_manager:worker-delete' pk=worker.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'task_manager:worker-update' pk=worker.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
{% endblock %}

templates/task_manager/worker_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} worker</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/worker_list.html
{% extends "base.html" %}

{% block content %}
	<h1>
		Worker list
		<a href="{% url 'task_manager:worker-create' %}" class="btn btn-primary link-to-page">
			Create
		</a>
	</h1>
	<form method="get" action="">

		{{ search_form }}
		<input type="submit" value="Search" class="btn btn-primary">
	</form>
	{% if worker_list %}
		<ul>
			{% for worker in worker_list %}
				<li>
					<a href="{% url "task_manager:worker-detail" pk=worker.id %} ">{{ worker.id }}</a>
					{{ worker.username }}
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>There are no workers in task_manager</p>
	{% endif %}
{% endblock %}